name: Build and Publish Docker image

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Node.js image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jamestop/node-vips:latest

      - name: Build and push Golang image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.golang
          push: true
          tags: jamestop/golang-vips:latest